services:
  main:
    restart: always
    build:
      context: .
      platforms:
        - linux/arm64
      dockerfile: Dockerfile
    environment:
      - ALPHAVANTAGE_KEY=<>
      - TELEGRAM_SUBSCRIBERS=<>
      - TELEGRAM_TOKEN=<>